CentOS-PaaS-SIG/contra-env-setup

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/minishift/defaults/main.yml
- playbooks/roles/minishift/tasks/init_minishift.yml
- playbooks/roles/minishift/tasks/install_minishift_bin.yml
- playbooks/roles/minishift/tasks/main.yml
- playbooks/roles/minishift/tasks/set_minishift_path.yml
- playbooks/roles/pipeline/defaults/main.yml
- playbooks/roles/pipeline/files/JenkinsfileContraSample1
- playbooks/roles/pipeline/files/pipeline-scc.yaml
- playbooks/roles/pipeline/tasks/add_scc.yml
- playbooks/roles/pipeline/tasks/build_new_app.yml
- playbooks/roles/pipeline/tasks/clone_pipeline.yml
- playbooks/roles/pipeline/tasks/get_set_project.yml
- playbooks/roles/pipeline/tasks/login_to_cluster.yml
- playbooks/roles/pipeline/tasks/main.yml
- playbooks/roles/pipeline/tasks/query_setup_cluster.yml
- playbooks/roles/pipeline/tasks/set_oc_client.yml
- playbooks/roles/pipeline/tasks/setup_containers.yml
- playbooks/roles/pipeline/tasks/setup_fedmsg_relay.yml
- playbooks/roles/pipeline/tasks/setup_jenkins_infra.yml
- playbooks/roles/pipeline/tasks/setup_sample_pipelines.yml
- playbooks/roles/pipeline/tasks/start_mcluster.yml
- playbooks/roles/pipeline/templates/contra-sample-pipeline1.xml.j2
- playbooks/roles/pipeline/templates/pipeline-scc.yaml.j2
- playbooks/roles/prereqs/tasks/install_kvm_plugin.yml
- playbooks/roles/prereqs/tasks/install_virtual_reqs.yml
- playbooks/roles/prereqs/tasks/main.yml
- playbooks/roles/prereqs/tasks/nested_virt.yml
- playbooks/setup.yml
- Copied over from ci-pipeline/dev_setup
> Initial commit to setup the repo

- README.md
- Since now we are minishift or openshift
> Updated README with a better heading

- playbooks/roles/os_temps/tasks/add_scc.yml
- create: scc_name_file.stdout != scc_file.stdout
- replace: scc_name_file.stdout == scc_file.stdout
> Change to compare filename to scc name

- playbooks/roles/create/tasks/clone_project_repo.yml
- playbooks/roles/create/tasks/main.yml
- git config --global http.sslVerify false
- {{ os_template_dir }}
> Add http.sslVerify false for git and fix loading templates

- test/README.md
- test/test_contra_env_setup.py
- test/test_contra_env_setup.yaml
* fixed the debug mode
* improve the comments in the parameter and test files
* supported Fedora and CentOS in the test
> Improved the test automation

- test/test_contra_env_setup.py
- test/test_contra_env_setup.yaml
- test_contra_env_setup.py checked by pylint
- Package management added in the parameter file
- Debug mode support stop and resume test to interact with the VM
fixes from review #21
> Some improvements in the test automation [v2]

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/cleanup/tasks/cleanup.yml
- playbooks/roles/os_temps/tasks/main.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
- playbooks/roles/prereqs/tasks/install_kvm_plugin.yml
- playbooks/roles/prereqs/tasks/install_virtual_reqs.yml
- playbooks/setup.yml
- test/test_contra_env_setup.yaml
- Update directories for pipeline
- remove start_minishift option since it isn't needed
- README changes from local server to local machine
- changed remote_user to user in globals
>  Updated README and changing options

- test/README.md
- test/ansible.cfg
- test/requirements.txt
- test/test_contra_env_setup.py
- test/test_contra_env_setup.yaml
- test/utils.py
- changed the qemu orchestration to virt-install
- support of centos7
- pylint and yamllint verification
- closing the issue #20 
- fixed recommendations for the review [v1] #27
> support for running tests on centos 7 [v2]

- playbooks/group_vars/all/global.yml
- playbooks/roles/cleanup/tasks/cleanup.yml
- playbooks/roles/minishift/tasks/init_minishift.yml
- playbooks/roles/minishift/tasks/install_minishift_bin.yml
- playbooks/roles/minishift/tasks/main.yml
- playbooks/roles/os_temps/tasks/add_scc.yml
- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/get_set_project.yml
- playbooks/roles/os_temps/tasks/install_oc_bin.yml
- playbooks/roles/os_temps/tasks/login_to_cluster.yml
- playbooks/roles/os_temps/tasks/main.yml
- playbooks/roles/os_temps/tasks/set_oc_client.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
- playbooks/roles/os_temps/tasks/start_mcluster.yml
- playbooks/roles/pipeline/tasks/main.yml
- playbooks/roles/pipeline/tasks/setup_pipelines.yml
- Set global to define the oc binary path and binar vars
- Change calls to shell: oc binary full path
- Change call for minishift to be full path
>  Change to use oc and minishift binaries full path

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/minishift/tasks/main.yml
- playbooks/roles/os_temps/tasks/add_scc.yml
- playbooks/roles/os_temps/tasks/login_to_cluster.yml
- playbooks/roles/os_temps/tasks/main.yml
- playbooks/roles/prereqs/tasks/setup_nested_virt.yml
- allow specification of cluster ip
- fix missing cast for prereqs
> Support use case when not using minishift

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/playbook_hooks/tasks/main.yml
- playbooks/setup.yml
- test/README.md
* looking to support the CVP project in "Post Deployment Tasks"
* fixing the issue #33
> Add the ability to specify adhoc oc commands

- playbooks/roles/os_temps/tasks/setup_os_templates.yml
Older version of origin-clients does not work with
short version (oc get is)
> Use longer version for imagestream

- playbooks/group_vars/all/global.yml
- s/startup_minishift/start_minishift/
> Fixed type-o of option

- playbooks/roles/prereqs/tasks/install_virtual_reqs.yml
- package works for all distros
> Change from using yum or dnf to use package

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/prereqs/tasks/check_os.yml
- playbooks/roles/prereqs/tasks/install_mac_pre_reqs.yml
- playbooks/roles/prereqs/tasks/main.yml
- playbooks/setup.yml
* Remove manual steps for a mac user.
* Get the OS of the host via playbook, not a user defined variable 
* The setup can now install homebrew, virtualbox, jq and gnu-tar for the user.
> Clean mac logic

- JenkinsfileStageMerge
This change adds a JenkinsfileStageMerge job which merges the pull request and rebuilds the testing containers if there were any changes to them in the changeset.
> Add a Jenkins merge job with container rebuilds

- JenkinsfileStageMerge
Use ci-pipeline _sendPRCommentforTags_ method for commenting PRs in the merge job.
Bugfixes for the merge job.
> Use ci-pipeline method for commenting PRs in the merge job

- playbooks/roles/os_temps/tasks/setup_os_templates.yml
It is simpler to copy and paste command while debugging.
> Use raw-ouput from jq instead of sed

- JenkinsfileStageMerge
Add completed status to merge job, set permitAll to false.
> Add completed status to merge job, bugfixes

- test/config/Dockerfiles/contra-env-setup-test-c7/prepare_and_test.sh
- test/config/Dockerfiles/contra-env-setup-test-c7/test_contra_env_setup.py
- test/config/Dockerfiles/contra-env-setup-test-f28/prepare_and_test.sh
- test/config/Dockerfiles/contra-env-setup-test-f28/test_contra_env_setup.py
Change the resource names being tested to match the ones from the contra-env-infra repo
> Adapt the CI tests to the contra-env-infra repo being used

- README.md
- playbooks/group_vars/all/global.yml
- Change examples and TOC
- Default to not run pre-reqs
> Update README.md with better more accurate examples

- playbooks/group_vars/all/global.yml
- https://github.com/minishift/minishift-centos-iso/releases/download/v1.14.0/minishift-centos7.iso
> Switch to using minishift iso

- test/config/Dockerfiles/contra-env-setup-test-c7/prepare_and_test.sh
- test/config/Dockerfiles/contra-env-setup-test-f28/prepare_and_test.sh
Set run_prereqs to true when running tests in the CI containers.
> Set run_prereqs to true when running test in the CI

- playbooks/roles/os_temps/tasks/setup_containers.yml
from ./playbooks/roles/os_temps/templates
> pickup templates  with extension .j2

- README.md
- playbooks/prepare_vm_for_minishift.yml
Add a playbook that prepares external VMs (fedora27+ or centos7) for usage with minishift including the option to setup nested virtualization on them.
> Add a playbook that prepares external VMs for usage with minishift

- playbooks/roles/cleanup/tasks/cleanup.yml
- Bug cleanup was not deleting ~/.kube correctly
- Don't delete project and sample directories let git clone do that
> Change cleanup

- playbooks/roles/cleanup/tasks/cleanup.yml
- playbooks/roles/create/tasks/clone_repos.yml
remove project directory exists and force_repo_clone is true
git fetch --all if project directory exists and force_repo_clone is true
> fix(Fix cleanup/clone): Cleanup project_dir git fetch --all

- playbooks/roles/cleanup/tasks/cleanup.yml
fix(Fix cleanup): cleanup should use the proper when conditional format for an AND statement
> fix(Fix cleanup): cleanup.yml

- playbooks/roles/os_temps/tasks/install_oc_bin.yml
* Check if the oc_exists.stdout_lines is empty
> Fix the issue with the oc_exists check

- playbooks/roles/minishift/tasks/install_minishift_bin.yml
- playbooks/roles/os_temps/tasks/install_oc_bin.yml
Updated `minishift` & `oc` download base URLs
> Update minishift & oc download URLs
