CentOS-PaaS-SIG/contra-env-setup

- playbooks/roles/minishift/tasks/install_minishift_bin.yml
- playbooks/roles/minishift/tasks/main.yml
- playbooks/roles/pipeline/tasks/add_scc.yml
- playbooks/roles/pipeline/tasks/main.yml
- playbooks/roles/pipeline/tasks/query_setup_cluster.yml
- playbooks/roles/pipeline/tasks/setup_containers.yml
- playbooks/roles/pipeline/tasks/setup_fedmsg_relay.yml
- playbooks/roles/pipeline/tasks/setup_jenkins_infra.yml
- playbooks/roles/pipeline/tasks/setup_sample_pipelines.yml
- playbooks/roles/prereqs/tasks/install_kvm_plugin.yml
- playbooks/roles/prereqs/tasks/main.yml
* fixed warning about deprecated:
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> fixed warning about deprecated 'include'

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/create/tasks/main.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/pipeline/tasks/setup_pipelines.yml
- playbooks/roles/pipeline/templates/contra-sample-pipeline-setup.xml.j2
- playbooks/roles/pipeline/templates/jenkins-pipeline-setup.xml.j2
- Update README with project name on command line and explanation
- Make sure template ends up in the write location
>  Update README and fix pipeline template destination

- playbooks/roles/pipeline/tasks/setup_pipelines.yml
After running ansible-lint to setup.yml reach this issues:
[ANSIBLE0011] All tasks should be named
/home/firemanxbr/GitHub/contra-env-setup/playbooks/roles/pipeline/tasks/setup_pipelines.yml:17
Task/Handler: set_fact __file__=/home/firemanxbr/GitHub/contra-env-setup/playbooks/roles/pipeline/tasks/setup_pipelines.yml all_pipelines={{ pipelines.files }} __line__=17
[ANSIBLE0011] All tasks should be named
/home/firemanxbr/GitHub/contra-env-setup/playbooks/roles/pipeline/tasks/setup_pipelines.yml:20
Task/Handler: set_fact __file__=/home/firemanxbr/GitHub/contra-env-setup/playbooks/roles/pipeline/tasks/setup_pipelines.yml all_pipelines={{ pipelines.files }} + {{ sample_pipelines.files }} __line__=20
[ANSIBLE0012] Commands should not change things if nothing needs doing …
> fixing some issues from ansible-lint in setup_pipelines.yml

- playbooks/group_vars/all/global.yml
- default changed for oc_version
- default changed for memory to be 8092
> Increase default version of OpenShift and up memory to 8092

- playbooks/roles/os_temps/tasks/setup_containers.yml
When validating and processing templates in the task file _playbooks/roles/os_temps/tasks/setup_containers.yml_, if an yaml file is not an Openshift template but a different kind of resource (e.g. SecurityContextConstraints), it should be skipped so the play doesn't fail on those steps.
> Skip non template yaml files when setting up containers

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/os_temps/tasks/main.yml
- option setup_helper_containers default = true
> Added option to disable loading of the helper containers

- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
It is possible for a build to have a New state when we query it the first time. We need to detect this and keep waiting
TASK [os_temps : debug] ********
ok: [localhost] => {
"msg": "End result of building the container image :: jenkins-cvp-slave-1   Docker    Git@CVP-133-func-tests-3   New (CannotRetrieveServiceAccount)             "
}
> Detect New state when querying for queued build

- playbooks/group_vars/all/global.yml
- playbooks/roles/prereqs/tasks/install_kvm_plugin.yml
- Moved to minishift v1.17.0
- Moved to docker-md-kvm driver to v1.10.0 for CentOS
- Updated new minishift.iso and location to s3 bucket link
> Updated versions of minishift and minishift.iso

- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/check_new_app.yml
- playbooks/roles/os_temps/tasks/check_os_templates.yml
- playbooks/roles/os_temps/tasks/handle_os_templates.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
This change introduces parallel builds in the _playbooks/roles/os_temps/setup_containers.yml_ task in the following manner:
1. All the information needed to initiate a build (params, buildconfig and imagestream checks etc.) gets proccessed and stored in corresponding hashes (dictionaries) for every template before the parallel builds get initiated (_setup_os_templates.yml_)
2. The builds get started in (relatively) rapid succesion, only waiting to check if the build is started - this helps to stagger the builds if the number of concurrent builds gets too large to be run at the same time (_handle_os_templates.yml_ which calls _build_new_app.yml_)
3. While the builds are running in parallel, the next step waits for the first build to be finished, and then for the second one and so on - the …
> Build container images in parallel

- playbooks/roles/os_temps/tasks/handle_os_templates.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
Fix for failed build cleanups - the backslash wasn't escaped.
> Fix backslash escaping for failed build cleanup filters

- README.md
- playbooks/roles/prereqs/tasks/install_virtual_reqs.yml
* Minor README update
* Using package instead of yum and dnf
(These are not blockers)
> Changed README and going to use package instead of yum and dnf

- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/check_new_app.yml
- playbooks/roles/os_temps/tasks/handle_os_templates.yml
- playbooks/roles/os_temps/tasks/main.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
This change handles the logging and cleanup of failed builds:
- Record which resources were created from the template when we run the _new-app_ command
- Clean all the recorded resources related to the template up if the build failed
- Detect if the build failed instantly (while we were waiting for it to be scheduled)
- Save logs of failed builds to log directory in _/tmp/contra-env-setup/logs/run-$timestamp/_
- If any of the builds failed, output debug message with the specific log directory location
> Log and cleanup failed builds

- playbooks/roles/minishift/tasks/main.yml
There are two similar cases, which both need to be covered:
1) `minishift status --profile <name>` will return "Does not exist",
in case someone already configured the profile with `minishift
profile set <name>`(or in case it got deleted with `minishift delete`).
2) `minishift status --profile <name>` will return error saying the
profile doesn't exist at all (e.g. this is the first time it is being
used and queried for). `minishift start` will then create that
profile.
This change brings support for case 2), by checking the result code of
the `minishift status` call.
> Create new minishift profile in case it was never created before

- playbooks/roles/prereqs/tasks/install_kvm_plugin.yml
The same task file is already being imported directly inside
playbooks/roles/prereqs/main.yml.
> Remove duplicated pkg install

- playbooks/roles/minishift/tasks/install_minishift_bin.yml
- playbooks/roles/os_temps/tasks/install_oc_bin.yml
Modified the commands which queries for the minishift and oc compressed binaries to cut off at the closing quote.
It seems the github links were updated recently, so without this change, the result of the command would be: 
"https://github.com/minishift/minishift/releases/download/v1.17.0/minishift-1.17.0-linux-amd64.tgz\" rel=\"nofollow"
> Fix the query command for the minishift and oc compressed binaries

- playbooks/group_vars/all/global.yml
* The default is 3.9 but we want to move to 3.10 OpenShift
> Bump version of OpenShift from 3.9 to 3.10

- playbooks/roles/os_temps/tasks/get_set_project.yml
- the check for an existing project fails if project
does not contain a description
> Support the case where project does not contain a display name

- playbooks/roles/minishift/tasks/install_minishift_bin.yml
Reverts CentOS-PaaS-SIG/contra-env-setup#75
Anonymous will use up connections to the github API I believe that is why I used curl to begin with.  With curl there is no limit
> Revert "use github api"

- playbooks/roles/minishift/tasks/main.yml
The ...| head -1 was swallowing the return code from
the minishift status --profile <name>, so it was 0 every time. This
update makes sure that the return code is preserved.
> More robust way of detecting if minishift profile exists

- playbooks/roles/minishift/tasks/main.yml
Before setting the configration options, like
skip-check-openshift-version, the configured profile needs to be active.
Before this change, the config options were applied to whatever profile
was configured as active, before the contra-env-setup got executed.
> Make sure configured minishift profile is active

- playbooks/roles/pipeline/tasks/main.yml
- If we want to skip over setting up container images
We need to then start minishift if defined
> setup or start minishift if true

- playbooks/roles/minishift/tasks/init_minishift.yml
- playbooks/setup.yml
In order to apply the cpu mode="host-passthrough" config to the VM, one needs
to stop the VM first. That was the case before, every time. However, at
least on Fedora, the cpu mode="host-passthrough" is configured by
default and thus there is no need to actually update the config and then
restart the VM. This considerably speeds up the the process.
Note about the setup_minishift and start_minishift flag values - there
are four possible cases:
1) 'setup_minishift == true and start_minishift == true' --- this will
result in creating and initializing brand new minishift profile, which
will be running after the init is done.
2) 'setup_minishift == true and start_minishift == false' --- this will
result in creating and initializing brand new minishift profile,
but it will be stopped at the end …
> No need to restart the VM if the config was not updated

- playbooks/roles/os_temps/tasks/setup_containers.yml
Fail the run if there are failed builds after going through all retries, output message directing to failed build log directory for this run.
> Fail the run if there are failed builds, direct to log directory

- playbooks/group_vars/all/global.yml
- playbooks/roles/prereqs/tasks/main.yml
Add a _setup_nested_virt_ option to _group_vars_ so we can skip the nested virtualization setup when installing prerequisites.
> Add setup_nested_virt option

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/os_temps/tasks/filter_templates.yml
- playbooks/roles/os_temps/tasks/handle_os_templates.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
This change adds _os_template_whitelist_ and _os_template_blacklist_ group variables (lists) that define which templates will be included/skipped according to these rules:
- All the template names in _os_template_blacklist_ will be skipped
- If _os_template_whitelist_ is defined, only the template names listed in it will be built
- If a template name shows up in both _os_template_whitelist_ and _os_template_blacklist_, it will be skipped, as the blacklist takes precedence
Both lists are empty by default, meaning that all the templates in the _os_template_dir_ will be built.
> Add template blacklist and whitelist

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/create/tasks/clone_repos.yml
Test for `pd_is_found.stat.exists` instead of incorrect `pd_is_found.stdout`
Update `force_repo_clone` to default = false in globals.yml
Update documentation to indicate `force_repo_clone default = false`
> Adjust repo cloning

- test/config/Dockerfiles/contra-env-setup-test-c7/prepare_and_test.sh
- test/config/Dockerfiles/contra-env-setup-test-c7/test_contra_env_setup.py
- test/config/Dockerfiles/contra-env-setup-test-f28/prepare_and_test.sh
- test/config/Dockerfiles/contra-env-setup-test-f28/test_contra_env_setup.py
This change limits _contra-env-setup_ CI tests to only build and test for _jenkins_ master and slave containers. 
This prevents errors stemming from changes to the _contra-env-sample-project_ (which will have its own CI for testing all the included containers) from blocking the _contra-env-setup_ CI.
Also, now the _test_jenkins_running_ test retries getting the jenkins login page in case the service didn't start up in time for the test run.
> Limit testing to jenkins containers

- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/check_new_app.yml
- playbooks/roles/os_temps/tasks/handle_os_templates.yml
- playbooks/roles/os_temps/tasks/main.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
Since Ansible 2.7 deprecated usage of include_tasks with variables defined inline, this change sets the required variables as facts before including the tasks. 
This change is backwards compatible and has been tested on Ansible 2.4.2, 2.6.5 and 2.7.0
> Fix include_tasks calls to work with Ansible 2.7

- playbooks/roles/os_temps/tasks/build_new_app.yml
Right now, we change to the config/ directory of the project when building with _new-app_ which doesn't work when we supply an alternative _os_template_dir_ parameter, especially if the config directory doesn't exist.
This change uses the os_templates_dir when determining where to go when building the templates, moving one level up from the supplied directory.
This doesn't modify the default behavior as the default value for os_templates_dir is "_config/s2i_", so we still change to "_config_" dir when building.
> Use templates dir when building the new app

- playbooks/roles/os_temps/tasks/filter_templates.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
Before this change, the new-app command used template label obtained in _oc process_ json output instead of template's name since the name isn't shown in json output.
As the label doesn't have to be the same as the template's name (or exist at all), this change uses _oc process --output=describe_ command in order to obtain the template's actual name so it can be used in further commands for building and filtering available templates.
> Use template name instead of its label when creating/filtering a new app

- playbooks/roles/os_temps/tasks/filter_templates.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
Use processed s2i template to obtain its name instead of the base one.
> Fix - use processed s2i template to obtain its name

- playbooks/roles/os_temps/tasks/login_to_cluster.yml
Fix issue #105
Signed-off-by: Barak Korren <bkorren@redhat.com>
> Fix issue when username/password contain spaces

- playbooks/group_vars/all/global.yml
- playbooks/roles/os_temps/tasks/login_to_cluster.yml
Add support for alternative ways to login to OpenShift:
1. Support skipping the loging process and assuming the user logged-in manually via the command line
2. Support logging in with a token instead of a username and a password
Resolves part #2 and #3 of issue #104
> Alternative OpenShift login methods

- playbooks/roles/os_temps/tasks/build_new_app.yml
The playbook contains a lot of code that deals with and prepares parameters for passing into OpenShift templates with instantiating them.
Only it seems that the values that were prepared were not being used for some reason. This patch attempts to fix that.
Signed-off-by: Barak Korren <bkorren@redhat.com>
> Fix passing parameters to OpenShift templates

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/create/tasks/clone_repos.yml
- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/main.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
* Update README with new examples and update current ones
* Example without minishift and sample project
* Modify globals
* versions of minishift/openshift
* new helper_container variables
* modify_scc to false
* Remove SAMPLE_PARAMS options
* Moved away from my fork since PR got merged
* Update TOC
> Move to use contra-env-infra templates

- playbooks/group_vars/all/global.yml
- playbooks/roles/minishift/tasks/main.yml
- playbooks/roles/os_temps/tasks/start_mcluster.yml
Enable optionally running minishift on an external VM (either local or remote). The VM needs to be setup according to [these steps](https://docs.okd.io/latest/minishift/using/run-against-an-existing-machine.html) in the minishift docs.
Adds three options to the contra-env-setup:
* minishift_external_vm_ip - the IP address of the external VM
* minishift_external_vm_user - the user with the sudo privileges on the external VM
* minishift_external_vm_ssh_key_location - the location of the configured ssh key
> Enable optionally running minishift on an external VM

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/os_temps/tasks/install_oc_bin.yml
Use the minishift home directory for caching oc binaries, as minishift uses `$MINISHIFT_HOME`  (~/.minishift) exclusively to store its cached binaries ([documentation](https://docs.okd.io/latest/minishift/using/basic-usage.html)). This should result in a minor speedup and also prevent minishift from calling the github api (also evading the dreaded rate limit) when using a non-default minishift profile.
> Use the minishift home directory for caching oc binaries

- playbooks/roles/os_temps/tasks/main.yml
Install only jq in the main os_temps role, don't include the installation of other virtual requirements as that bypasses the run_prereqs option.
> Install only jq in os_temps task, don't install virtual requirements

- .gitignore
This fixes submodule mapping errors while git cloning
> [Test]: Update .gitignore to avoid stage errors

- playbooks/group_vars/all/global.yml
- playbooks/roles/create/tasks/clone_repos.yml
- playbooks/roles/minishift/tasks/init_minishift.yml
- playbooks/roles/minishift/tasks/main.yml
- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/check_new_app.yml
- playbooks/roles/os_temps/tasks/filter_templates.yml
- playbooks/roles/os_temps/tasks/handle_os_templates.yml
- playbooks/roles/os_temps/tasks/main.yml
- playbooks/roles/os_temps/tasks/setup_containers.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
- playbooks/roles/pipeline/tasks/main.yml
- playbooks/roles/pipeline/tasks/setup_pipelines.yml
- playbooks/roles/prereqs/tasks/setup_nested_virt.yml
- fixed all when statements for compound conditionals
- fixed project_repo to point to contra-env-infra
- only load containers from samples directory when setup_sample_project=true
- issues with container-tools so blacklist for now
- it loads as contra-env-infra and fedora instead of container-tools and fails
> Consistent simplified conditionals

- playbooks/roles/os_temps/tasks/setup_os_templates.yml
Previous two tasks have names "Get template name from the yaml file",
"Get template name from querying the cluster". So we shoudl use template
also here and not buildconfig
> Fix confusing name of tasks

- playbooks/roles/os_temps/tasks/setup_os_templates.yml
There was an assumption that ImageStream is the 1st one in the list.
There was an assumption that BuildConfig is the 2nd one in the list.
And therefore we could get a name of wrong object.
> Fix extracting ImageStream/BuildConfig from template

- playbooks/roles/prereqs/tasks/install_kvm_plugin.yml
This fixes KVM driver pulling step as it currently fails in local env due to jinja2 templating[1]. Adjusting this as per docs[2]
[1] - http://pastebin.test.redhat.com/704084
[2] - https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#hey-wait-a-yaml-gotcha
> Fix KVM driver installation: Add quotes to jinja2 var

- playbooks/roles/os_temps/tasks/main.yml
Skip jq install if it's already installed on the machine so we can run it on unprivileged machines/containers.
> Skip jq install if it's already installed on the machine

- playbooks/roles/os_temps/tasks/install_oc_bin.yml
The Release page of github has changed to include checksums for each file, so the current query gets the checksum of the file we search for instead of the hyperlink to it which breaks the setup. 
This change should fix it and make it a bit more future proof.
> Fix the query for the oc compressed binary to search links only

- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/check_new_app.yml
When checking the status of container builds always check the latest one.
Especially important when rebuilding failed builds or updating existing ones.
> When checking the status of container builds always check the latest one

- README.md
- playbooks/group_vars/all/global.yml
- playbooks/roles/os_temps/tasks/build_new_app.yml
- playbooks/roles/os_temps/tasks/setup_os_templates.yml
Add the `force_template_overwrite` flag that allows us to delete all resources belonging to templates we want to replace on the existing cluster so we can build those templates from scratch. 
Works well in combination with template whitelist/blacklist.
> Add support for template overwriting

- playbooks/setup.yml
Remember the git `http.sslverify` config setting and revert it to the original value after setup is done.
> Reset git http.sslverify setting after setup is done

- playbooks/roles/prereqs/tasks/install_virtual_reqs.yml
Added conditionals to install python3-libselinux and python3-dnf when
the version of Fedora is greater than 30.
This resolves #158
> ADD conditions to install proper pkgs in Fedora 30

- playbooks/roles/os_temps/tasks/get_set_project.yml
When an ansible vault with a name registry_vault is present we will attempt to add the quay registry credentials to the secrets and add the secret to the builder and deployer service accounts.
> If a quay image registry vault is defined add the credentials to the secret.

- playbooks/README.md
- playbooks/provision_openstack_instance.yml
The changes made are adding an Ansible playbook to automate the provisioning of an Open Stack Instance and a Reame.txt file which describes the playbook and how to run the playbook and setup the credentials. 
This playbook provides easier setup and saves time.
> Automate provisioning OpenStack instance manually

- playbooks/roles/cleanup/tasks/cleanup.yml
Let say you already configure your cluster localy and have client
certificate for system:admin in ~/.kube/config and also session for
developer user which already accepted insecure connection to cluster.
Removing directory results in failure for "setup_minishift: false"
```
TASK [os_temps : Login to the Openshift cluster with a token] ******************************************
skipping: [localhost]
TASK [os_temps : Login to the Openshift cluster with a username and a password] ************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/root/.minishift/cache/oc/v3.11.0/linux/oc", "
login", "", "--username=developer", "--password=developer", "--insecure-skip-tls-verify=true"], "delta":
"0:00:00.166926", "end": "2020-09-09 07:13:59.272772", "msg": "non-zero return …
```
> Do not remove .kube directory without setup_minishift
